import type {
  OpportunityCompanyEvent,
  OpportunityContextEntity,
  OpportunityCoreTarget,
  OpportunityIndicatorSnapshot,
  OpportunityRawNews,
} from './types';

const now = '2026-05-23T08:00:00.000Z';

export const seedCoreWatchlist: OpportunityCoreTarget[] = [
  {
    id: 1,
    symbol: 'MU',
    name: 'Micron Technology',
    market: 'US',
    asset_type: 'stock',
    theme: 'HBM / memory cycle',
    priority: 1,
    is_active: true,
    notes: 'Watch HBM, DRAM, NAND cycle, and Samsung certification progress.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 2,
    symbol: 'NVDA',
    name: 'NVIDIA',
    market: 'US',
    asset_type: 'stock',
    theme: 'AI compute',
    priority: 1,
    is_active: true,
    notes: 'Watch data center demand, supply constraints, and valuation pressure.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 3,
    symbol: 'AMD',
    name: 'Advanced Micro Devices',
    market: 'US',
    asset_type: 'stock',
    theme: 'AI accelerator competition',
    priority: 2,
    is_active: true,
    notes: 'Watch MI series ramp and competitive gap versus NVDA.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 4,
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    market: 'US',
    asset_type: 'etf',
    theme: 'Nasdaq 100 beta',
    priority: 1,
    is_active: true,
    notes: 'Core DCA and market temperature target.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 5,
    symbol: 'SMH',
    name: 'VanEck Semiconductor ETF',
    market: 'US',
    asset_type: 'etf',
    theme: 'semiconductor basket',
    priority: 2,
    is_active: true,
    notes: 'Watch semiconductor theme crowding and trend strength.',
    created_at: now,
    updated_at: now,
  },
];

export const seedContext: OpportunityContextEntity[] = [
  {
    id: 1,
    core_symbol: 'MU',
    related_symbol: null,
    related_name: 'Samsung Memory',
    market: 'GLOBAL',
    relation_type: 'competitor',
    relation_strength: 0.8,
    reason: 'Samsung HBM certification progress affects MU competition and supply-demand framing.',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 2,
    core_symbol: 'MU',
    related_symbol: null,
    related_name: 'SK Hynix',
    market: 'GLOBAL',
    relation_type: 'competitor',
    relation_strength: 0.75,
    reason: 'SK Hynix is a key supply-side reference for HBM.',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 3,
    core_symbol: 'MU',
    related_symbol: null,
    related_name: 'CXMT',
    market: 'CN',
    relation_type: 'industry_signal',
    relation_strength: 0.55,
    reason: 'Domestic DRAM capacity expansion affects long-term supply narratives.',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 4,
    core_symbol: 'NVDA',
    related_symbol: 'TSM',
    related_name: 'TSMC',
    market: 'US',
    relation_type: 'supplier',
    relation_strength: 0.85,
    reason: 'Advanced packaging and capacity constraints affect NVDA delivery cadence.',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 5,
    core_symbol: 'SMH',
    related_symbol: 'ASML',
    related_name: 'ASML',
    market: 'US',
    relation_type: 'etf_holding',
    relation_strength: 0.65,
    reason: 'ASML orders influence semiconductor capital spending cycle judgment.',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
];

export const seedRawNews: OpportunityRawNews[] = [
  {
    id: 1,
    source: 'seed',
    title: 'Micron highlights sustained HBM demand from AI server customers',
    summary:
      'Micron management says HBM demand remains stronger than planned and supply remains tight.',
    url: null,
    published_at: '2026-05-23T01:00:00.000Z',
    hash: 'seed-mu-hbm-demand-2026-05-23',
    raw_json: { source: 'seed' },
    created_at: now,
  },
  {
    id: 2,
    source: 'seed',
    title: 'Samsung HBM certification timeline reportedly slips again',
    summary:
      'A delay in Samsung HBM certification could keep near-term high-end supply tighter.',
    url: null,
    published_at: '2026-05-23T02:00:00.000Z',
    hash: 'seed-samsung-hbm-delay-2026-05-23',
    raw_json: { source: 'seed' },
    created_at: now,
  },
  {
    id: 3,
    source: 'seed',
    title: 'NVIDIA data center demand remains robust as cloud capex expands',
    summary:
      'Large cloud customers continue to expand AI infrastructure budgets.',
    url: null,
    published_at: '2026-05-23T03:00:00.000Z',
    hash: 'seed-nvda-demand-2026-05-23',
    raw_json: { source: 'seed' },
    created_at: now,
  },
  {
    id: 4,
    source: 'seed',
    title: 'AMD AI accelerator checks improve but competition remains intense',
    summary:
      'Channel checks suggest improving interest in AMD accelerators, with pricing pressure from incumbents.',
    url: null,
    published_at: '2026-05-23T04:00:00.000Z',
    hash: 'seed-amd-accelerator-2026-05-23',
    raw_json: { source: 'seed' },
    created_at: now,
  },
  {
    id: 5,
    source: 'seed',
    title: 'Semiconductor ETF momentum remains strong after rapid 20-day rally',
    summary:
      'SMH trend is strong, but short-term returns and volume show crowding risk.',
    url: null,
    published_at: '2026-05-23T05:00:00.000Z',
    hash: 'seed-smh-overheat-2026-05-23',
    raw_json: { source: 'seed' },
    created_at: now,
  },
];

export const seedCompanyEvents: OpportunityCompanyEvent[] = [
  {
    id: 1,
    symbol: 'MU',
    company_name: 'Micron Technology',
    theme: 'HBM / memory cycle',
    event_type: 'demand',
    event_direction: 'positive',
    importance_score: 86,
    event_summary: 'HBM demand remains strong and supply tight, supporting MU narrative.',
    evidence_news_ids: [1],
    published_at: '2026-05-23T01:00:00.000Z',
    raw_payload: { seed: true },
    created_at: now,
  },
  {
    id: 2,
    symbol: 'Samsung Memory',
    company_name: 'Samsung Memory',
    theme: 'HBM / memory cycle',
    event_type: 'competition',
    event_direction: 'positive',
    importance_score: 78,
    event_summary:
      'Samsung HBM certification delay may keep competitive supply pressure lower for MU.',
    evidence_news_ids: [2],
    published_at: '2026-05-23T02:00:00.000Z',
    raw_payload: { maps_to_core_symbol: 'MU', seed: true },
    created_at: now,
  },
  {
    id: 3,
    symbol: 'NVDA',
    company_name: 'NVIDIA',
    theme: 'AI compute',
    event_type: 'demand',
    event_direction: 'positive',
    importance_score: 88,
    event_summary: 'Cloud AI capex remains strong and supports NVDA demand.',
    evidence_news_ids: [3],
    published_at: '2026-05-23T03:00:00.000Z',
    raw_payload: { seed: true },
    created_at: now,
  },
  {
    id: 4,
    symbol: 'AMD',
    company_name: 'Advanced Micro Devices',
    theme: 'AI accelerator competition',
    event_type: 'product',
    event_direction: 'mixed',
    importance_score: 62,
    event_summary:
      'AMD accelerator interest improves, but competitive pressure remains high.',
    evidence_news_ids: [4],
    published_at: '2026-05-23T04:00:00.000Z',
    raw_payload: { seed: true },
    created_at: now,
  },
  {
    id: 5,
    symbol: 'SMH',
    company_name: 'VanEck Semiconductor ETF',
    theme: 'semiconductor basket',
    event_type: 'price_action',
    event_direction: 'mixed',
    importance_score: 70,
    event_summary:
      'SMH momentum is strong but recent gains raise short-term overheating risk.',
    evidence_news_ids: [5],
    published_at: '2026-05-23T05:00:00.000Z',
    raw_payload: { seed: true, overheat: true },
    created_at: now,
  },
];

export const seedIndicators: OpportunityIndicatorSnapshot[] = [
  {
    symbol: 'MU',
    close: 128,
    pct_change_5d: 3.2,
    pct_change_20d: 8.4,
    pct_from_ma500: 18.2,
    drawdown_1y: -7.6,
    volume_ratio: 1.15,
    risk_level: 'medium',
  },
  {
    symbol: 'NVDA',
    close: 1240,
    pct_change_5d: 7.8,
    pct_change_20d: 17.5,
    pct_from_ma500: 42.1,
    drawdown_1y: -2.1,
    volume_ratio: 1.55,
    risk_level: 'high',
  },
  {
    symbol: 'AMD',
    close: 176,
    pct_change_5d: 2.1,
    pct_change_20d: 5.2,
    pct_from_ma500: 11.4,
    drawdown_1y: -15.2,
    volume_ratio: 1.05,
    risk_level: 'medium',
  },
  {
    symbol: 'QQQ',
    close: 468,
    pct_change_5d: 1.7,
    pct_change_20d: 4.4,
    pct_from_ma500: 13.1,
    drawdown_1y: -4.5,
    volume_ratio: 0.96,
    risk_level: 'low',
  },
  {
    symbol: 'SMH',
    close: 244,
    pct_change_5d: 6.4,
    pct_change_20d: 15.6,
    pct_from_ma500: 27.8,
    drawdown_1y: -3.4,
    volume_ratio: 1.72,
    risk_level: 'high',
  },
];
